2024-10-27 16:11:25,291 INFO: Login attempt for user: string@gmail.com [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:79]
2024-10-27 16:14:43,542 INFO: Login attempt for user: string@gmail.com [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:85]
2024-10-27 16:24:04,156 INFO: Attempting to register user: string [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:62]
2024-10-27 16:24:05,692 INFO: User registered successfully: string [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:77]
2024-10-27 16:26:11,169 INFO: Login attempt for user: string@gmail.com [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:88]
2024-10-27 16:26:11,686 INFO: User logged in successfully: string@gmail.com [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:100]
2024-10-27 16:34:49,423 INFO: Attempting to register user: mola [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:62]
2024-10-27 16:34:49,954 INFO: User registered successfully: mola [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:77]
2024-10-27 16:36:18,227 INFO: Login attempt for user: schema@gold.co.ke [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:88]
2024-10-27 16:36:18,755 INFO: User logged in successfully: schema@gold.co.ke [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:100]
2024-10-27 16:43:34,397 INFO: Login attempt for user: string@gmail.com [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:88]
2024-10-27 16:43:36,063 INFO: User logged in successfully: string@gmail.com [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:100]
2024-10-27 16:47:44,747 INFO: Login attempt for user: string@gmail.com [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:88]
2024-10-27 16:47:45,959 INFO: User logged in successfully: string@gmail.com [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:100]
2024-10-27 16:48:38,101 INFO: Login attempt for user: schema@gold.co.ke [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:88]
2024-10-27 16:48:38,482 INFO: User logged in successfully: schema@gold.co.ke [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:100]
2024-10-27 16:52:17,204 INFO: Login attempt for user: schema@gold.co.ke [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:88]
2024-10-27 16:52:17,599 INFO: User logged in successfully: schema@gold.co.ke [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:100]
2024-10-27 16:59:12,770 INFO: Login attempt for user: string@gmail.com [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:88]
2024-10-27 16:59:14,128 INFO: User logged in successfully: string@gmail.com [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:100]
2024-10-27 18:26:40,008 INFO: Login attempt for user: string@gmail.com [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:91]
2024-10-27 19:19:50,167 INFO: Fetching locations for user: 2 [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:145]
2024-10-27 19:27:28,223 INFO: Fetching locations for user: 2 [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:147]
2024-10-27 19:27:28,233 INFO: Retrieved 0 locations for user: 2 [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:149]
2024-10-27 19:29:10,180 INFO: Creating new location for user: 2 [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:162]
2024-10-27 19:31:12,367 INFO: Creating new location for user: 2 [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:163]
2024-10-27 19:31:12,372 ERROR: Error creating location for user 2: 'description' is an invalid keyword argument for Location [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:171]
Traceback (most recent call last):
  File "C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py", line 164, in create_location
    db_location = LocationModel(**location.model_dump(), user_id=current_user.id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\env\Lib\site-packages\sqlalchemy\orm\state.py", line 571, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\env\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\env\Lib\site-packages\sqlalchemy\orm\state.py", line 569, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\env\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 2167, in _declarative_constructor
    raise TypeError(
TypeError: 'description' is an invalid keyword argument for Location
2024-10-27 19:34:00,518 INFO: Creating new location for user: 2 [in C:\Users\skmola.TELKOM\Desktop\projects\python\mapsapi\Routes\routes.py:163]
